title: github-page-demo
email: test@163.com
description: github-page-demo 
baseurl: "" 
url: "https://zzw-project.github.io/github-page-demo/" 

# Build settings
theme: minima

plugins:
  - jekyll-feed
