title: github-page-demo
email: your-email@example.com
description: github-page-demo
baseurl: ""
url: "https://zzw-project.github.io/github-page-demo/" 

# Build settings
theme: minima
permalink: none
future : true
